# Generated by Django 5.1 on 2024-11-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_creditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='cvv',
            field=models.CharField(default='000', max_length=3),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='expiry_date',
            field=models.CharField(max_length=7),
        ),
    ]
